apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.bastian-somon.fr/moov-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: moov-secret
      imagePullSecrets:
        - name: registry-creds
#          volumeMounts:
#            - name: nginx-config
#              mountPath: /etc/nginx/nginx.conf
#              subPath: nginx.conf
#      volumes:
#        - name: nginx-config
#          configMap:
#            name: nginx-configmap
#            items:
#              - key: nginx.conf
#                path: nginx.conf
