version: "3.9"

services:

  # Service for the database
  moov-db:
    container_name: moov-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-moov}
    volumes:
      - db-data:/var/lib/postgresql/data

  # Service for the backend
  moov-api:
    container_name: moo-api
    image: bastiansmn/moov-container-registry:server-latest
    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-moov}
      DB_PORT: ${DB_PORT:-5432}
      ORIGIN: ${ORIGIN:-https://moov.bastian-somon.fr}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    depends_on:
      - moov-db
    links:
      - moov-db
    ports:
      - "${PORT:-3000}:3000"

volumes:
  db-data:
  pgadmin-data:

networks:
  default:
    external:
      name: apps-network
