const { jwtAuth, verifyLog, requestsStats } = require("../middleware/index");
const controller = require("../controller/user");

module.exports = (app) => {
   app.use((_req, res, next) => {
      res.header(
         "Access-Control-Allow-Headers",
         "x-access-token, Origin, Content-Type, Accept"
      );
      next();
   });
   app.get(
      "/api/user/getUserByUUID",
      [
         jwtAuth.verifyToken,
      ],
      controller.getUserByUUID
   );
   app.put(
      "/api/user/setNotifications",
      [
         jwtAuth.verifyToken,
         requestsStats.saveRequest
      ],
      controller.setUserNotifications
   );
   app.put(
      "/api/user/setRecommandations",
      [
         jwtAuth.verifyToken,
         requestsStats.saveRequest
      ],
      controller.setUserRecommandations
   );
   app.get(
      "/api/user/getUsers",
      [
         jwtAuth.verifyToken,
         verifyLog.isAdmin,
         requestsStats.saveRequest
      ],
      controller.getUsers
   );
   app.put(
      "/api/user/updateRoles",
      [
         jwtAuth.verifyToken,
         verifyLog.isAdmin,
         requestsStats.saveRequest
      ],
      controller.updateRoles
   );
   app.put(
      "/api/user/setCity",
      [
         jwtAuth.verifyToken
      ],
      controller.setCity
   );
   app.put(
      "/api/user/setPreferedRadius",
      [
         jwtAuth.verifyToken
      ],
      controller.setPreferedRadius
   );
   app.post(
      "/api/user/create",
      [
         jwtAuth.verifyToken,
         verifyLog.isAdmin,
         verifyLog.validateEmailAndUsername,
         verifyLog.validatePassword,
         verifyLog.roleExist,
         requestsStats.saveRequest
      ],
      controller.createUser
   );
   app.get(
      "/api/user/me",
      [
         jwtAuth.verifyToken,
         requestsStats.saveRequest
      ],
      controller.recommandedEvents
   );
   app.get(
      "/api/user/getSavedEvents",
      [
         jwtAuth.verifyToken
      ],
      controller.getSavedEvents
   );
   app.post(
      "/api/user/saveEvent",
      [
         jwtAuth.verifyToken
      ],
      controller.saveEvent
   );
   app.delete(
      "/api/user/unsaveEvent",
      [
         jwtAuth.verifyToken
      ],
      controller.unsaveEvent
   );
   app.delete(
      "/api/user/delete",
      [
         jwtAuth.verifyToken,
      ],
      controller.deleteUser
   )
};