export default interface City {
   city_id: string,
   name: string,
   api_base_link: string,
   dataset_name: string,
   title_field: string,
   description_field: string,
   image_field: string,
   url_field: string,
   placename_field: string,
   timing_field: string,
   date_start_field: string,
   date_end_field: string,
   latlon_field: string,
   city_field: string,
   district_field: string,
   is_active: boolean,
}
