apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: moov-ingress
  namespace: moov
spec:
  ingressClassName: nginx
  rules:
    - host: moov.bastian-somon.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moov-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: moov-backend
                port:
                  number: 3000