name: Moov CD

on:
  push:
    branches:
    - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login and push to container registry
        run: |
            echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr -u ${{ secrets.REGISTRY_USER }} --password-stdin
            docker build -t registry.bastian-somon.fr/moov-backend:latest backend
            docker push registry.bastian-somon.fr/moov-backend:latest

  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login and push to container registry
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr -u ${{ secrets.REGISTRY_USER }} --password-stdin
          docker build -t registry.bastian-somon.fr/moov-frontend:latest frontend
          docker push registry.bastian-somon.fr/moov-frontend:latest

  deploy-infra:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Action with Python 2.x fixes
        uses: davi020/kubernetes-action@V1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: apply -k infra/application

  rollout-infra:
    needs: [deploy-infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Action with Python 2.x fixes
        uses: davi020/kubernetes-action@V1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment node -n moov

      - name: Kubernetes Action with Python 2.x fixes
        uses: davi020/kubernetes-action@V1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment nginx -n moov
