name: Moov CD

on: [push]

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Stop and remove the containers
        run: docker-compose -f docker-compose.server.yml down

      - name: Set up env file
        run: |
          touch .env
          echo "PG_EMAIL=${{ secrets.PG_EMAIL }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env

      - name: Source the .env variables to the current shell
        run: |  
          export $(grep -v '^#' .env | xargs)

      - name: Run docker-compose
        run: docker-compose -f docker-compose.server.yml up -d

  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: cd frontend && npm i && npm run build
      - name: Copy dist files to vps
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: frontend/vue-app/*
          target: /var/www/html/moov
          strip_components: 2
