name: Moov CD

on: [push]

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push new backend image to container registry
#        uses: docker/build-push-action@v2
#        with:
#          file: backend/Dockerfile
#          push: true
#          tags: bastiansmn/moov-container-registry:server-latest

      - uses: actions/checkout@v3

      - name: Login and push to container registry
        run: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker build -t bastiansmn/moov-container-registry:server-latest backend
            docker push bastiansmn/moov-container-registry:server-latest

      - name: Copy docker-compose.server.yml file to vps
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: docker-compose.server.yml
          target: /apps/moov

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /apps/moov
            docker compose -f docker-compose.server.yml down
            docker pull bastiansmn/moov-container-registry:server-latest
            echo "" > .env
            echo "PG_EMAIL=${{ secrets.PG_EMAIL }}" >> .env
            echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
            echo "EMAIL=${{ secrets.EMAIL }}" >> .env
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
            echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env
            export $(grep -v '^#' .env | xargs)
            docker compose -f docker-compose.server.yml up -d --build

  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create the .env file for frontend
        run: |
          touch frontend/.env
          echo "VITE_MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> frontend/.env
          echo "VITE_BACKEND_URL=${{ secrets.BACKEND_URL }}" >> frontend/.env
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: cd frontend && npm i && npm run build
      - name: Copy dist files to vps
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: frontend/vue-app/*
          target: /var/www/html/moov
          strip_components: 2
