name: Moov CI

on: [push]

jobs:
  build-database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up env file
        run: |
          echo "PG_EMAIL=${{ secrets.PG_EMAIL }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env

      - name: Run docker-compose
        run: docker-compose -f docker-compose.db.yml up -d

  build-backend:
    runs-on: ubuntu-latest
    needs: build-database
    steps:
      - uses: actions/checkout@v3

      - name: Create the .env file for backend
        run: |
          touch backend/.env
          echo "EMAIL=${{ secrets.EMAIL }}" >> backend/.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> backend/.env
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> backend/.env

      - name: Source the .env variables to the current shell
        run: |
          export $(grep -v '^#' backend/.env | xargs)

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install and start
        run: |
          cd backend
          npm i
          npm test

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create the .env file for frontend
        run: |
          touch frontend/.env
          echo "VITE_MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> frontend/.env
          echo "VITE_BACKEND_URL=${{ secrets.BACKEND_URL }}" >> frontend/.env

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install and build
        run: |
          cd frontend
          npm i
          npm run build
